### ISSUE TITLE
No hover effect

### ISSUE THREAD

**Issue by Pratham271** [TBD54566975/developer.tbd.website#849] opened 2023-10-08 06:32 UTC
https://github.com/TBD54566975/developer.tbd.website/assets/83640434/ee527b36-4dc8-484b-b5d5-7795409234ac

As shown in the video there is no hover effect on the Legal, Code of Conduct and TBD Home links

**Comment by Pratham271** [comment] 2023-10-08 06:32
I would like to fix this by working on it

**Comment by captain-Akshay** [comment] 2023-10-08 13:13
@Pratham271 sorry to say but i have already a issue related to this #827
but you are in the right path buddy!

**Comment by Pratham271** [comment] 2023-10-09 04:45
Can I work on this one you have multiple issues opened already brother

**Comment by angiejones** [comment] 2023-10-09 08:51
thank you, however this is a duplicate of #827

**Closed by angiejones** 2023-10-09 08:51 UTC
